server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/catkill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: peng1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 25
      min-idle: 5
      initial-size: 5
      query-timeout: 600
      max-wait: 300000


jedis:
  pool: #redis配置地址
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 2000
    config:
      maxTotal: 100
      maxIdle: 2
      maxWaitMillis: 10000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.avaj.ekill.model
